# render.yaml - Configuração Completa (Frontend + Backend)

services:
  # Serviço para o backend Node.js (API)
  - type: web
    name: mcj-backend
    env: node
    
    # Comando de Build: Instala dependências do backend e frontend
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    
    # Comando de Start: Inicia o servidor Node.js
    startCommand: npm start
    
    # Variáveis de Ambiente para o Backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://lnxofsqwfkmpphjsgecb.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxueG9mc3F3ZmttcHBoanNnZWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTgwMDAsImV4cCI6MjA3MDgzNDAwMH0.L22_jfMFHJCokN0Vp4ZFpwN6rU5m_hzeKlbAO_3IlE4
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxueG9mc3F3ZmttcHBoanNnZWNiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTI1ODAwMCwiZXhwIjoyMDcwODM0MDAwfQ.YQlCUBhfJKJGGJHGJHGJHGJHGJHGJHGJHGJHGJHGJHG
      - key: JWT_SECRET
        value: sua_jwt_secret_super_segura_aqui_123456789
      - key: REACT_APP_SUPABASE_URL
        value: https://lnxofsqwfkmpphjsgecb.supabase.co
      - key: REACT_APP_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxueG9mc3F3ZmttcHBoanNnZWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTgwMDAsImV4cCI6MjA3MDgzNDAwMH0.L22_jfMFHJCokN0Vp4ZFpwN6rU5m_hzeKlbAO_3IlE4

# Habilita a criação de Previews para Pull Requests
previewsEnabled: true
