# render.yaml - Configuração para Site Estático (React)

services:
  # Serviço para o frontend React
  - type: static
    name: mcj-frontend
    # O ambiente para sites estáticos é 'static'
    env: static 
    
    # Comando de Build: Instala as dependências e builda apenas o frontend.
    # O script 'render-build' que criamos continua perfeito para isso.
    buildCommand: npm run render-build
    
    # Diretório de Publicação: Onde os arquivos estáticos (HTML, CSS, JS) estão após o build.
    staticPublishPath: client/build

    # Configuração para Single Page Application (SPA)
    # Isso garante que o roteamento do React funcione corretamente.
    # Todas as requisições são redirecionadas para o index.html.
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    # Variáveis de Ambiente para o Frontend (usadas durante o build)
    envVars:
      - key: REACT_APP_SUPABASE_URL
        value: https://lnxofsqwfkmpphjsgecb.supabase.co # Cole sua URL do Supabase aqui
      - key: REACT_APP_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxueG9mc3F3ZmttcHBoanNnZWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTgwMDAsImV4cCI6MjA3MDgzNDAwMH0.L22_jfMFHJCokN0Vp4ZFpwN6rU5m_hzeKlbAO_3IlE4 # Cole sua chave anon do Supabase aqui

# Habilita a criação de Previews para Pull Requests
previewsEnabled: true
