# render.yaml - Configuração para Aplicação Full-Stack (Node.js + React)

services:
  # Serviço principal que roda o backend e serve o frontend
  - type: web
    name: mcj-worship-app
    env: node
    # Garante que o Render use uma versão do Node compatível com seu package.json
    nodeVersion: "18" 
    
    # Comando de Build: Instala dependências do backend e do frontend, e depois builda o frontend.
    buildCommand: npm run render-build
    
    # Comando de Início: Inicia o seu servidor Express após a build.
    startCommand: npm start

    # Variáveis de Ambiente para Backend e Frontend
    envVars:
      # Para o Backend (Node.js)
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        # IMPORTANTE: Cole aqui a string de conexão do POOLER do Supabase
        value: "postgres://postgres:[SUA_SENHA]@[HOST_DO_SUPABASE]:6543/postgres"
      - key: JWT_SECRET
        # O Render vai gerar um valor aleatório e seguro para esta chave
        generateValue: true
      
      # Para o Frontend (React) - Usadas durante o `npm run build`
      - key: REACT_APP_SUPABASE_URL
        value: "https://SEU-PROJETO-ID.supabase.co" # Cole sua URL do Supabase aqui
      - key: REACT_APP_SUPABASE_ANON_KEY
        value: "COLE_SUA_CHAVE_ANON_AQUI" # Cole sua chave anon do Supabase aqui

# Habilita a criação de Previews para Pull Requests
previewsEnabled: true
